baseURL = "https://student-lt.tech/"
#baseURL = ""
languageCode = "js"
canonifyurls = true
title = "#学生LT"
publishdir = "public"
googleAnalytics = "UA-106772445-1"
theme = "minimal"

[Params]
Description="学生エンジニア、集まれ。"
